HomeWorkWeek1/Models/客戶聯絡人.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWorkWeek1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 客戶聯絡人
    {
        public int Id { get; set; }
        public int 客戶Id { get; set; }
        public string 職稱 { get; set; }
        public string 姓名 { get; set; }
        public string Email { get; set; }
        public string 手機 { get; set; }
        public string 電話 { get; set; }
        public int iscancel { get; set; }
    
        public virtual 客戶資料 客戶資料 { get; set; }
    }
}

HomeWorkWeek1/Controllers/客戶聯絡人Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClosedXML.Excel;
using HomeWorkWeek1.ActionFilter;
using HomeWorkWeek1.Models;
using X.PagedList;

namespace HomeWorkWeek1.Controllers
{
    public class 客戶聯絡人Controller : Controller
    {
        客戶聯絡人Repository repo = RepositoryHelper.Get客戶聯絡人Repository();
        
        private Entities db = new Entities();
        private int pageSize = 5;
        // GET: 客戶聯絡人
        [LogActionFilterAttribute]
        public ActionResult Index(int Page = 1)
        {
            var dropdown = repo.All().Distinct();
            SelectList selectlist = new SelectList(dropdown, "職稱", "職稱");
            ViewBag.selectlist = selectlist;
            return View(repo.All().OrderBy(p => p.Id).ToPagedList(Page, pageSize));
        }

        // GET: 客戶聯絡人/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶聯絡人 客戶聯絡人 = repo.Find(id.Value);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            return View(客戶聯絡人);
        }

        // GET: 客戶聯絡人/Create
        public ActionResult Create()
        {
            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱");
            return View();
        }

        // POST: 客戶聯絡人/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,客戶Id,職稱,姓名,Email,手機,電話")] 客戶聯絡人 客戶聯絡人)
        {
            if (ModelState.IsValid)
            {
                repo.Add(客戶聯絡人);
                repo.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }

            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        // GET: 客戶聯絡人/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶聯絡人 客戶聯絡人 = repo.Find(id.Value);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        // POST: 客戶聯絡人/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,客戶Id,職稱,姓名,Email,手機,電話")] 客戶聯絡人 客戶聯絡人)
        {
            if (ModelState.IsValid)
            {
                var db = repo.UnitOfWork.Context;
                db.Entry(客戶聯絡人).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        // GET: 客戶聯絡人/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶聯絡人 客戶聯絡人 = repo.Find(id.Value);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            return View(客戶聯絡人);
        }

        // POST: 客戶聯絡人/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            客戶聯絡人 客戶聯絡人 =repo.Find(id);
            repo.Delete(客戶聯絡人);
            repo.UnitOfWork.Commit();
            return RedirectToAction("Index");
        }
        public ActionResult Title(string title)
        {
            var dropdown = repo.All().Distinct();
            SelectList selectlist = new SelectList(dropdown, "職稱", "職稱");
            ViewBag.selectlist = selectlist;

            var 客戶資料 = repo.Title(title);
            return View("Index", 客戶資料);
        }
        [HttpPost]
        public FileResult Export()
        {

            DataTable dt = new DataTable("Grid");
            dt.Columns.AddRange(new DataColumn[] { new DataColumn("職稱"),
                                            new DataColumn("姓名"),
                                            new DataColumn("Email"),
                                            new DataColumn("手機"),
                new DataColumn("電話")
               });

            var contacts = repo.All();

            foreach (var contact in contacts)
            {
                dt.Rows.Add(contact.職稱, contact.姓名, contact.Email, contact.手機, contact.電話);
            }

            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Grid.xlsx");
                }
            }
        }



        public JsonResult IsEmailExists(string Email)
        {
            //check if any of the UserName matches the UserName specified in the Parameter using the ANY extension method.  
            return Json(!db.客戶聯絡人.Any(x => x.Email == Email), JsonRequestBehavior.AllowGet);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repo.UnitOfWork.Context.Dispose();
            }
            base.Dispose(disposing);
        }
        [HttpPost]
        [LogActionFilterAttribute]
        [Route("BatchUpdate")]
        [HandleError(ExceptionType = typeof(DbEntityValidationException), View = "Error_DbEntityValidationException")]
        public ActionResult BatchUpdate(聯絡人BatchVM[] data)
        { 

            if (ModelState.IsValid)
            {
                foreach (var vm in data)
                {
                    var 客戶聯絡人 = db.客戶聯絡人.Find(vm.Id);
                    客戶聯絡人.職稱 = vm.職稱;
                    客戶聯絡人.手機 = vm.手機;
                    客戶聯絡人.電話 = vm.電話;
                }

                
                db.SaveChanges();
                
                return RedirectToAction("Index");
            }

            ViewData.Model = repo.All().Take(10);
            var dropdown = repo.All().Distinct();
            SelectList selectlist = new SelectList(dropdown, "職稱", "職稱");
            ViewBag.selectlist = selectlist;
            return View("Index");
        }



    }
}

HomeWorkWeek1/Views/客戶聯絡人/Create.cshtml
@model HomeWorkWeek1.Models.客戶聯絡人

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶聯絡人</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.客戶Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.職稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.職稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.職稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.姓名, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.姓名, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.姓名, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.手機, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.手機, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.手機, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeWorkWeek1/Views/客戶聯絡人/Delete.cshtml
@model HomeWorkWeek1.Models.客戶聯絡人

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>客戶聯絡人</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.職稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.職稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.姓名)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.姓名)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.手機)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.手機)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HomeWorkWeek1/Views/客戶聯絡人/Details.cshtml
@model HomeWorkWeek1.Models.客戶聯絡人

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>客戶聯絡人</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.職稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.職稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.姓名)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.姓名)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.手機)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.手機)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HomeWorkWeek1/Views/客戶聯絡人/Edit.cshtml
@model HomeWorkWeek1.Models.客戶聯絡人

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶聯絡人</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.客戶Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.職稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.職稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.職稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.姓名, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.姓名, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.姓名, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.手機, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.手機, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.手機, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeWorkWeek1/Views/客戶聯絡人/Index.cshtml
@model IEnumerable<HomeWorkWeek1.Models.客戶聯絡人>
@using X.PagedList;
@using X.PagedList.Mvc;


@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Title", "客戶聯絡人", FormMethod.Get, null))
{
    @Html.Label("職稱：")


    @Html.DropDownList("title", (SelectList)ViewBag.selectlist, "=Deafult=", new { @onchange = "this.form.submit();" })
}


@using (Html.BeginForm("BatchUpdate", "客戶聯絡人", FormMethod.Post, null))
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.職稱)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.姓名)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.手機)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.電話)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
            </th>
            <th></th>
        </tr>
        @{
            var data = Model.ToArray();
            int i;
        }
        @for (i = 0; i < data.Length; i++)
        {
            @Html.HiddenFor(modelItem => data[i].Id)
            <tr>
                <td>
                    @Html.EditorFor(modelItem => data[i].職稱)
                    @Html.ValidationMessageFor(model => data[i].職稱, "", new { @class = "text-danger" })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => data[i].姓名)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => data[i].Email)
                </td>
                <td>
                    @Html.EditorFor(modelItem => data[i].手機)
                    @Html.ValidationMessageFor(model => data[i].手機, "", new { @class = "text-danger" })
                </td>
                <td>
                    @Html.EditorFor(modelItem => data[i].電話)
                    @Html.ValidationMessageFor(Model => data[i].電話, "", new { @class = "text-danger" })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => data[i].客戶資料.客戶名稱)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = data[i].Id })
                    @Html.ActionLink("Details", "Details", new { id = data[i].Id })
                    @Html.ActionLink("Delete", "Delete", new { id = data[i].Id })
                </td>
            </tr>
        }

    </table>

    <input type="submit" />
}

@Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))

HomeWorkWeek1/Views/客戶聯絡人/index1.cshtml
@model IEnumerable<HomeWorkWeek1.Models.聯絡人BatchVM>

@{
    ViewBag.Title = "index1";
}

<h2>index1</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.職稱)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.手機)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.電話)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.職稱)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.手機)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.電話)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>