HomeWorkWeek1/Models/客戶銀行資訊.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWorkWeek1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 客戶銀行資訊
    {
        public int Id { get; set; }
        public int 客戶Id { get; set; }
        public string 銀行名稱 { get; set; }
        public int 銀行代碼 { get; set; }
        public Nullable<int> 分行代碼 { get; set; }
        public string 帳戶名稱 { get; set; }
        public string 帳戶號碼 { get; set; }
        public int iscancel { get; set; }
    
        public virtual 客戶資料 客戶資料 { get; set; }
    }
}

HomeWorkWeek1/Controllers/客戶銀行資訊Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClosedXML.Excel;
using HomeWorkWeek1.Models;

namespace HomeWorkWeek1.Controllers
{
    public class 客戶銀行資訊Controller : Controller
    {
        private Entities db = new Entities();
        客戶銀行資訊Repository repo = RepositoryHelper.Get客戶銀行資訊Repository();
        // GET: 客戶銀行資訊
        public ActionResult Index()
        {
            var 客戶銀行資訊 =  repo.All();
            return View(客戶銀行資訊.ToList());
        }

        // GET: 客戶銀行資訊/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶銀行資訊 客戶銀行資訊 = repo.Find(id.Value);
            if (客戶銀行資訊 == null)
            {
                return HttpNotFound();
            }
            return View(客戶銀行資訊);
        }

        // GET: 客戶銀行資訊/Create
        public ActionResult Create()
        {

            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱");
            return View();
        }

        // POST: 客戶銀行資訊/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,客戶Id,銀行名稱,銀行代碼,分行代碼,帳戶名稱,帳戶號碼")] 客戶銀行資訊 客戶銀行資訊)
        {
            if (ModelState.IsValid)
            {
                
                repo.Add(客戶銀行資訊);
                repo.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }

            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱", 客戶銀行資訊.客戶Id);
            return View(客戶銀行資訊);
        }

        // GET: 客戶銀行資訊/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶銀行資訊 客戶銀行資訊 = repo.Find(id.Value);
            if (客戶銀行資訊 == null)
            {
                return HttpNotFound();
            }
            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱", 客戶銀行資訊.客戶Id);
            return View(客戶銀行資訊);
        }

        // POST: 客戶銀行資訊/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,客戶Id,銀行名稱,銀行代碼,分行代碼,帳戶名稱,帳戶號碼")] 客戶銀行資訊 客戶銀行資訊)
        {
            if (ModelState.IsValid)
            {
                var db = repo.UnitOfWork.Context;
                db.Entry(客戶銀行資訊).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱", 客戶銀行資訊.客戶Id);
            return View(客戶銀行資訊);
        }

        // GET: 客戶銀行資訊/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶銀行資訊 客戶銀行資訊 = repo.Find(id.Value);
            if (客戶銀行資訊 == null)
            {
                return HttpNotFound();
            }
            return View(客戶銀行資訊);
        }

        // POST: 客戶銀行資訊/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            客戶銀行資訊 客戶銀行資訊 = repo.Find(id);
            repo.Delete(客戶銀行資訊);
            repo.UnitOfWork.Commit();
             
            return RedirectToAction("Index");
        }

        public ActionResult Search(string keyword)
        {

            var 銀行資訊 = repo.Searchname(keyword);

            return View("Index", 銀行資訊);
        }
        [HttpPost]
        public FileResult Export()
        {

            DataTable dt = new DataTable("Grid");
            dt.Columns.AddRange(new DataColumn[] { new DataColumn("銀行名稱"),
                                            new DataColumn("銀行代碼"),
                                            new DataColumn("分行代碼"),
                                            new DataColumn("帳戶名稱"),
                new DataColumn("帳戶號碼")
               });

            var banks = repo.All();

            foreach (var bank in banks)
            {
                dt.Rows.Add(bank.銀行名稱, bank.銀行代碼, bank.分行代碼, bank.帳戶名稱, bank.帳戶號碼);
            }

            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Grid.xlsx");
                }
            }
        }
      
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repo.UnitOfWork.Context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HomeWorkWeek1/Views/客戶銀行資訊/Create.cshtml
@model HomeWorkWeek1.Models.客戶銀行資訊

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶銀行資訊</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.客戶Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.銀行名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行代碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行代碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.銀行代碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.分行代碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.分行代碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.分行代碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.帳戶名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶號碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶號碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.帳戶號碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeWorkWeek1/Views/客戶銀行資訊/Delete.cshtml
@model HomeWorkWeek1.Models.客戶銀行資訊

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>客戶銀行資訊</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.銀行名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.銀行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.分行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.分行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶號碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶號碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HomeWorkWeek1/Views/客戶銀行資訊/Details.cshtml
@model HomeWorkWeek1.Models.客戶銀行資訊

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>客戶銀行資訊</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.銀行名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.銀行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.分行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.分行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶號碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶號碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HomeWorkWeek1/Views/客戶銀行資訊/Edit.cshtml
@model HomeWorkWeek1.Models.客戶銀行資訊

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶銀行資訊</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.客戶Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.銀行名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行代碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行代碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.銀行代碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.分行代碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.分行代碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.分行代碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.帳戶名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶號碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶號碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.帳戶號碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeWorkWeek1/Views/客戶銀行資訊/Index.cshtml
@model IEnumerable<HomeWorkWeek1.Models.客戶銀行資訊>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Search", "客戶銀行資訊", FormMethod.Get, null))
{
    @Html.TextBox("keyword", null, new { placeholder = "請輸入關鍵字" })
    <input type="submit" />
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.銀行名稱)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.銀行代碼)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.分行代碼)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.帳戶名稱)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.帳戶號碼)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.銀行名稱)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.銀行代碼)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.分行代碼)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.帳戶名稱)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.帳戶號碼)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.客戶資料.客戶名稱)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>
@using (Html.BeginForm("Export", "客戶銀行資訊", FormMethod.Post))
{
    <input type="submit" value="Export" />
}